### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by bersace** [rheinwerk-verlag/pganonymize#39]
Hi,

Your project's name conflicts with [PostgreSQL Anonymizer](https://labs.dalibo.com/postgresql_anonymizer) by @daamien from Dalibo. It seems that your project started 2 years after @daamien's one.

What do you think of this ?

Anyway, this project is very interesting !

Regards,

**Comment by hkage** [comment]
Hello,

to be honest I have seen this project during my researches and it wasn't a solution for our development case (we needed a client side software). It gave me a basic idea what I was looking for and wanted an own Python solution, that uses a simple, human readable defintion syntax. But I didn't notice, that I named this project in the same way. 

I didn't intend to confuse others by chossing the same name. So maybe I have to rename this project and choose another one that can be used instead of.

Thanks for the hint!

Best Regards

**Comment by hkage** [comment]
I informed the other project's author, that I will rename this project as soon as possible. Thanks again for reporting!

**Comment by bersace** [comment]
Yep, the projects have the same purpose but the two implementation matches different use cases and constraints. I wasn't contesting the usefulness of you work. Thanks for your answer.

**Comment by hkage** [comment]
I left the package name to `pganonymize`, which seems to be unique right now (currently I only see another project named "pganonymizer" within PyPi) and renamed the project name and all documentation ocurrences to "pganonymize", too.

**Comment by bersace** [comment]
You're awesome.

**Comment by daamien** [comment]
Thanks, I added a link to your project in our documentation: 

https://postgresql-anonymizer.readthedocs.io/en/latest/links/

Have a nice day

**Comment by hkage** [comment]
Thanks for the link! I will also add one link to your project in our documentation.

Best regards

**Comment by hkage** [comment]
The code changes of the project renaming will be part of the upcoming release 0.8.0 and are merged to the development.

**Comment by hkage** [comment]
> Thanks, I added a link to your project in our documentation:
> 
> https://postgresql-anonymizer.readthedocs.io/en/latest/links/
> 
> Have a nice day

Our updated Sphinx documentation with the reference to your project is available under https://pganonymize.readthedocs.io/en/latest/links.html#links

Thanks again and best regards!
